apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
      scrape_timeout: 5s
      external_labels:
        monitor: "csvserver"
    scrape_configs:
      - job_name: "csvserver-metrics"
        scrape_interval: 5s
        static_configs:
          - targets: ["192.168.59.100:30007"]
        metrics_path: /metrics
