kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-vol
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/prometheus-metrics"
