kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: research-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: prometheus-vol
  resources:
    requests:
      storage: 1Gi
